### ISSUE TITLE
azure_sdk does not work work with ruby-2.4.0-preview2

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#534]
Installation of `azure_sdk` on Ruby version `ruby-2.4.0-preview2` requires `json` version at least `2.0` while [azure-storage](https://github.com/Azure/azure-storage-ruby/blob/master/azure-storage.gemspec#L45) gem requires `json` version `1.8`. Due to this installation fails on  `ruby-2.4.0-preview2` 

cc:
@yaxia

Installation Error log:
```
vishrut@visshamac azure_sdk (master) $ gem install azure_sdk-0.7.0.gem 
Fetching: faraday_middleware-0.10.0.gem (100%)
Successfully installed faraday_middleware-0.10.0
Fetching: azure-core-0.1.5.gem (100%)
Successfully installed azure-core-0.1.5
Building native extensions.  This could take a while...
ERROR:  Error installing azure_sdk-0.7.0.gem:
	ERROR: Failed to build gem native extension.

    current directory: /Users/vishrut/.rvm/gems/ruby-2.4.0-preview2/gems/json-1.8.3/ext/json/ext/generator
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/bin/ruby -r ./siteconf20161031-37811-auzlzv.rb extconf.rb
creating Makefile

current directory: /Users/vishrut/.rvm/gems/ruby-2.4.0-preview2/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/vishrut/.rvm/gems/ruby-2.4.0-preview2/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c:861:25: error: use of undeclared identifier 'rb_cFixnum'
    } else if (klass == rb_cFixnum) {
                        ^
generator.c:863:25: error: use of undeclared identifier 'rb_cBignum'
    } else if (klass == rb_cBignum) {
                        ^
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2122:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2308:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2180:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2146:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2141:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2137:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2122:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2308:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2180:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2146:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2142:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2137:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2122:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2308:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2180:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2147:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2141:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2137:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2122:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2308:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2180:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2146:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2141:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2137:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2122:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2308:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2180:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2146:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2141:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2137:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2122:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2308:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2180:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2146:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2141:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vishrut/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:2137:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings and 2 errors generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/vishrut/.rvm/gems/ruby-2.4.0-preview2/gems/json-1.8.3 for inspection.
Results logged to /Users/vishrut/.rvm/gems/ruby-2.4.0-preview2/extensions/x86_64-darwin-15/2.4.0/json-1.8.3/gem_make.out
```

**Comment by yaxia** [comment]
Noted. I will estimate the impact of updating the dependencies in azure-storage where the main concern is about the Ruby 1.9.3 compatibility. Please stay tuned. Thanks.

**Comment by sarangan12** [comment]
Issue has been resolved. Tested locally. Closing the issue
